<a href="https://colab.research.google.com/github/luca-boldrin/IPABDN/blob/main/testML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!ls -local


total 16
drwxr-xr-x 1 root 4096 Feb 23 15:07 .
drwxr-xr-x 1 root 4096 Feb 27 07:36 ..
drwxr-xr-x 4 root 4096 Feb 23 15:07 .config
drwxr-xr-x 1 root 4096 Feb 23 15:07 sample_data


In [2]:
!pwd


/content


In [3]:
!whoami


root


this is some text

this is other text

In [4]:
#@ this should not execute

In [5]:
!cd sample_data

In [7]:
!cd sample_data; ls -al

total 55512
drwxr-xr-x 1 root root     4096 Feb 23 14:26 .
drwxr-xr-x 1 root root     4096 Feb 23 14:26 ..
-rwxr-xr-x 1 root root     1697 Jan  1  2000 anscombe.json
-rw-r--r-- 1 root root   301141 Feb 23 14:26 california_housing_test.csv
-rw-r--r-- 1 root root  1706430 Feb 23 14:26 california_housing_train.csv
-rw-r--r-- 1 root root 18289443 Feb 23 14:26 mnist_test.csv
-rw-r--r-- 1 root root 36523880 Feb 23 14:26 mnist_train_small.csv
-rwxr-xr-x 1 root root      930 Jan  1  2000 README.md


In [3]:
data = [{'customer': 'Hi there, what time do you open tomorrow for lunch?',
  'tags': ['opening', 'closing', 'hours']},
 {'customer': 'Can I speak to your manager?', 'tags': ['customer_support']},
 {'customer': 'The food was amazing thank you!',
  'tags': ['customer_support', 'feedback']},
 {'customer': 'What type of products do you have?',
  'tags': ['products', 'menu', 'inventory', 'food']},
 {'customer': 'How late is your kitchen open?',
  'tags': ['opening', 'hours', 'closing']},
 {'customer': 'My order was prepared incorrectly, how can I get this fixed?',
  'tags': ['customer_support']},
 {'customer': 'What kind of meats do you have?',
  'tags': ['menu', 'products', 'inventory', 'food']},
 {'customer': 'When does your dining room open?',
  'tags': ['opening', 'hours']},
 {'customer': 'When do you open for dinner?',
  'tags': ['opening', 'hours', 'closing']},
 {'customer': 'How do I contact you?',
  'tags': ['contact', 'customer_support']}]

In [4]:

print (data)

[{'customer': 'Hi there, what time do you open tomorrow for lunch?', 'tags': ['opening', 'closing', 'hours']}, {'customer': 'Can I speak to your manager?', 'tags': ['customer_support']}, {'customer': 'The food was amazing thank you!', 'tags': ['customer_support', 'feedback']}, {'customer': 'What type of products do you have?', 'tags': ['products', 'menu', 'inventory', 'food']}, {'customer': 'How late is your kitchen open?', 'tags': ['opening', 'hours', 'closing']}, {'customer': 'My order was prepared incorrectly, how can I get this fixed?', 'tags': ['customer_support']}, {'customer': 'What kind of meats do you have?', 'tags': ['menu', 'products', 'inventory', 'food']}, {'customer': 'When does your dining room open?', 'tags': ['opening', 'hours']}, {'customer': 'When do you open for dinner?', 'tags': ['opening', 'hours', 'closing']}, {'customer': 'How do I contact you?', 'tags': ['contact', 'customer_support']}]


In [5]:
data_i = [x['customer'] for x in data]; print (data_i)

['Hi there, what time do you open tomorrow for lunch?', 'Can I speak to your manager?', 'The food was amazing thank you!', 'What type of products do you have?', 'How late is your kitchen open?', 'My order was prepared incorrectly, how can I get this fixed?', 'What kind of meats do you have?', 'When does your dining room open?', 'When do you open for dinner?', 'How do I contact you?']


In [6]:
data_o = [x['tags'] for x in data]; print (data_o)

[['opening', 'closing', 'hours'], ['customer_support'], ['customer_support', 'feedback'], ['products', 'menu', 'inventory', 'food'], ['opening', 'hours', 'closing'], ['customer_support'], ['menu', 'products', 'inventory', 'food'], ['opening', 'hours'], ['opening', 'hours', 'closing'], ['contact', 'customer_support']]


In [7]:
assert (len(data_o)== 10)

In [8]:
# !pip install scikit-learn

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(data_i)

In [ ]:
print(X)

In [35]:
X.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [12]:
X.shape[1]


43

In [52]:
words = vectorizer.get_feature_names_out()
print(words)

['amazing' 'can' 'contact' 'dining' 'dinner' 'do' 'does' 'fixed' 'food'
 'for' 'get' 'have' 'hi' 'how' 'incorrectly' 'is' 'kind' 'kitchen' 'late'
 'lunch' 'manager' 'meats' 'my' 'of' 'open' 'order' 'prepared' 'products'
 'room' 'speak' 'thank' 'the' 'there' 'this' 'time' 'to' 'tomorrow' 'type'
 'was' 'what' 'when' 'you' 'your']


In [21]:
print(data_i[0], data_o[0], isinstance(data_o[0], list))

Hi there, what time do you open tomorrow for lunch? ['opening', 'closing', 'hours'] True


In [31]:
from sklearn.preprocessing import MultiLabelBinarizer

Y = MultiLabelBinarizer().fit_transform(data_o)

In [38]:
Y

array([[1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
Y.shape

(10, 10)

In [49]:
mlb = MultiLabelBinarizer()
mlb.fit_transform(data_o)
mlb.classes_

array(['closing', 'contact', 'customer_support', 'feedback', 'food',
       'hours', 'inventory', 'menu', 'opening', 'products'], dtype=object)

In [50]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(random_state=1)
model = MultiOutputClassifier(forest, n_jobs=-1)

In [51]:
model.fit(X,Y)

MultiOutputClassifier(estimator=RandomForestClassifier(random_state=1),
                      n_jobs=-1)

In [56]:
txt = "Hi, when do you open?"
input_vector = vectorizer.transform([txt])
input_vector

<1x43 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [57]:
print(input_vector)

  (0, 5)	1
  (0, 12)	1
  (0, 24)	1
  (0, 40)	1
  (0, 41)	1


In [58]:
output_vector = model.predict(input_vector)
print(output_vector)

[[0 0 0 0 0 1 0 0 1 0]]


In [59]:
preds = {}
classes = mlb.classes_
for i, val in enumerate(output_vector[0]):
    preds[classes[i]] = val

In [60]:
preds

{'closing': 0,
 'contact': 0,
 'customer_support': 0,
 'feedback': 0,
 'food': 0,
 'hours': 1,
 'inventory': 0,
 'menu': 0,
 'opening': 1,
 'products': 0}

In [61]:
def label_predictor(txt):
    # pred
    input_vector = vectorizer.transform([txt])
    output_vector = model.predict(input_vector)
    preds = {}
    classes = mlb.classes_
    for i, val in enumerate(output_vector[0]):
        preds[classes[i]] = val
    return preds

In [71]:
label_predictor("what products do you have")

{'closing': 0,
 'contact': 0,
 'customer_support': 0,
 'feedback': 0,
 'food': 1,
 'hours': 0,
 'inventory': 1,
 'menu': 1,
 'opening': 0,
 'products': 1}

# Export Model for Re-Use

In [72]:
import pickle
# classes
# model
# vectorizer

model_data = {
    "classes": list(mlb.classes_),
    "model": model,
    "vectorizer": vectorizer
}

with open("model.pkl", 'wb') as f:
    pickle.dump(model_data, f)

In [73]:
model_loaded_data = {}

with open("model.pkl", 'rb') as f:
    model_loaded_data = pickle.loads(f.read())

def label_predictor_from_export(txt='Hello world',
                                vectorizer=None,
                                model=None,
                                classes=[],
                                *args,
                                **kwargs):
    # pred
    assert(vectorizer!=None)
    assert(model != None)
    input_vector = vectorizer.transform([txt])
    output_vector = model.predict(input_vector)
    assert(len(output_vector[0]) == len(classes))
    preds = {}
    classes = mlb.classes_
    for i, val in enumerate(output_vector[0]):
        preds[classes[i]] = val
    return preds

label_predictor_from_export("When does your kitchen close?", **model_loaded_data)

{'closing': 0,
 'contact': 0,
 'customer_support': 0,
 'feedback': 0,
 'food': 0,
 'hours': 1,
 'inventory': 0,
 'menu': 0,
 'opening': 1,
 'products': 0}

# Store Dataset with Pandas

In [75]:
!pip install pandas
import pandas as pd

In [77]:
df = pd.DataFrame(data)
df.head(n=100)

customer  \
0  Hi there, what time do you open tomorrow for l...   
1                       Can I speak to your manager?   
2                    The food was amazing thank you!   
3                 What type of products do you have?   
4                     How late is your kitchen open?   
5  My order was prepared incorrectly, how can I g...   
6                    What kind of meats do you have?   
7                   When does your dining room open?   
8                       When do you open for dinner?   
9                              How do I contact you?   

                                tags  
0          [opening, closing, hours]  
1                 [customer_support]  
2       [customer_support, feedback]  
3  [products, menu, inventory, food]  
4          [opening, hours, closing]  
5                 [customer_support]  
6  [menu, products, inventory, food]  
7                   [opening, hours]  
8          [opening, hours, closing]  
9        [contact, customer_support]

# Creating a Rest API Model Service

In [88]:
!pip install fastapi uvicorn requests
API_APP_PATH = 'app.py' # pathlib, os.path




In [89]:
# from fastapi import FastAPI

# app = FastAPI()

# @app.get("/")
# def homepage_view():
#     return {"Hello": "World"}%%writefile $API_APP_PATH

%%writefile $API_APP_PATH

import pickle
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

model_data = {}

with open("model.pkl", 'rb') as f:
    model_data = pickle.loads(f.read())


class CustomerInput(BaseModel):
    query:str

def predict(txt='Hello world',
                vectorizer=None,
                model=None,
                classes=[],
                *args,
                **kwargs):
    # pred
    assert(vectorizer!=None)
    assert(model != None)
    input_vector = vectorizer.transform([txt])
    output_vector = model.predict(input_vector)
    assert(len(output_vector[0]) == len(classes))
    preds = {}
    for i, val in enumerate(output_vector[0]):
        preds[classes[i]] = int(val)
    return preds

@app.post("/predict")
def predict_view(customer_input:CustomerInput):
    # storing this query data -> SQL database
    my_pred = predict(customer_input.query, **model_data)
    return {"query": customer_input.query, "predictions": my_pred}

# @app.post('/train')

Overwriting app.py


# use rest service

In [ ]:
import requests

json = {
    "query": "When do you open?"
}

r = requests.post("http://localhost:8080/predict", json=json)
print(r.json())